### ISSUE TITLE
Allow facts.j2 override

### ISSUE THREAD

**Issue by kakawait** [silpion/ansible-tomcat#13]
Your tomcat role create an ansible fact for tomcat to expose tomcat version https://github.com/silpion/ansible-tomcat/blob/master/templates/facts.j2

But it could be cool to allow user to customize the facts, indeed I wanted to put catalina_base on it to easily manipulate it later on post_process task

**Comment by spul** [comment]
Hi,

this is something I want to do/use way more in future versions. Feel free to add any information configurable from defaults/main.yml and go for PR :)

**Comment by spul** [comment]
[1.1.0](https://github.com/silpion/ansible-tomcat/tree/1.1.0) integrates #15, #16, #17. Again thank you very much for your suggestions and work.
