### ISSUE TITLE
Missing folders on catalina instance

### ISSUE THREAD

**Issue by kakawait** [silpion/ansible-tomcat#14]
I wanted to know if it's possible to add the following folder for catalina instances:

- `lib`
- `bin`

based on https://github.com/silpion/ansible-tomcat/blob/master/vars/main.yml#L19-23 `tomcat_instance_dirs` is not overrideable, but I don't think it's mandatory we should just add missing keys tomcat's folders.

**Comment by spul** [comment]
Integrated with #17 and released with [1.1.0](https://github.com/silpion/ansible-tomcat/tree/1.1.0).
