### ISSUE TITLE
Permission denied when used with Vagrant

### ISSUE THREAD

**Issue by eddgrant** [silpion/ansible-tomcat#2]
When using this role through the Vagrant Ansible provisioner the ``local_action`` which writes data in to ``/usr/local/src/ansible`` fails with the following permissions error:

    TASK: [groover.tomcat | Install local ansible data path directory (local)] **** 
    <127.0.0.1> REMOTE_MODULE file state=directory owner=0 group=0 mode=2777 dest=/usr/local/src/ansible/data
    failed: [tc1 -> 127.0.0.1] => {"failed": true, "parsed": false}
    invalid output was: Traceback (most recent call last):
      File "/home/egrant/.ansible/tmp/ansible-tmp-1416997610.02-204869902985063/file", line 1675, in <module>
        main()
      File "/home/egrant/.ansible/tmp/ansible-tmp-1416997610.02-204869902985063/file", line 216, in main
        os.mkdir(curpath)
    OSError: [Errno 13] Permission denied: '//usr/local/src/ansible'

    FATAL: all hosts have already failed -- aborting

I think this might be a similar issue to https://github.com/silpion/ansible-packerio/issues/1 but I can't quite figure out a good approach. I initially tried running the role with ``sudo: true`` and configuring ``ansible.ask_sudo_pass = true`` in my VagrantFile, however this didn't make any difference. I subsequently realised that the ``local_action`` task doesn't use sudo anyway so am guessing this is why this doesn't work?.

I may be missing something obvious in my setup, would you be able to elaborate on the intended way of running this? 

Many thanks,

Edd

**Comment by spul** [comment]
Hi, finaly had the chance to fix that.
