### ISSUE TITLE
wrong permissions for conf

### ISSUE THREAD

**Issue by ijovic-wcs** [silpion/ansible-tomcat#20]
Hi,

upon using this role in a playbook like
```yml
- hosts: stage02
  vars_files:
    - vars.yml

  roles:
  - { role: groover.java}
  - { role: groover.tomcat}
```

where vars.yml contains only the `tomcat_default_catalina_opts` and stage02 is a remote server assessed as a non-root user which is a sudoer

When running this playbook via
`sudo ansible-playbook deploy.yml`

everything gets installed, but when I try to run tomcat manually with `/opt/tomcat/apache-tomcat-7.0.62/bin/catalina.sh run` I get back the following log:
```
Using CATALINA_BASE:   /opt/tomcat/apache-tomcat-7.0.62
Using CATALINA_HOME:   /opt/tomcat/apache-tomcat-7.0.62
Using CATALINA_TMPDIR: /opt/tomcat/apache-tomcat-7.0.62/temp
Using JRE_HOME:        /opt/java/oracle/jdk1.8.0_45
Using CLASSPATH:       /opt/tomcat/apache-tomcat-7.0.62/bin/bootstrap.jar:/opt/tomcat/apache-tomcat-7.0.62/bin/tomcat-juli.jar
Oct 15, 2015 10:24:30 AM org.apache.catalina.startup.Catalina load
WARNING: Unable to load server configuration from [/opt/tomcat/apache-tomcat-7.0.62/conf/server.xml]
Oct 15, 2015 10:24:30 AM org.apache.catalina.startup.Catalina load
WARNING: Permissions incorrect, read permission is not allowed on the file.
Oct 15, 2015 10:24:30 AM org.apache.catalina.startup.Catalina load
WARNING: Unable to load server configuration from [/opt/tomcat/apache-tomcat-7.0.62/conf/server.xml]
Oct 15, 2015 10:24:30 AM org.apache.catalina.startup.Catalina load
WARNING: Permissions incorrect, read permission is not allowed on the file.
Oct 15, 2015 10:24:30 AM org.apache.catalina.startup.Catalina start
SEVERE: Cannot start server. Server instance is not configured
```

upon more inspection I noticed that
a) entire `/opt/tomcat` along with subdirectories is owned by root
b) `/opt/tomcat/apache-tomcat-7.0.62/conf` is both owned by root AND has 600 permissions, meaning the running `tomcat` user cannot read the configuration - it's available only for root

Of course, running via `sudo service tomcat start` doesn't work either

**Comment by derjust** [comment]
Was confused, too:
Check `/srv/tomcat....` - there you find all the instance files with the proper permissions.
`service` / init scripts worked like a charm from the beginning.

**Comment by spul** [comment]
Yeah, um, we could have the documentation updated to reflect that /opt (when using default configuration) is just CATALINA_HOME and does not run any webapp and instances (CATALINA_BASE) are installed in /srv.

**Comment by derjust** [comment]
+1 for making that more prominent in the documentation.
It makes somewhat sense with the multi-instance-option that you can also figure - but it doesn't appeared to me that this also affecting my single-deployment.

It is working flawless now - just figuring that out was a bit of a head scratch...

**Comment by akankshajain** [comment]
How did you fix this issue? what are the correct permissions required?
