### ISSUE TITLE
EL 7 support

### ISSUE THREAD

**Issue by kakawait** [silpion/ansible-tomcat#6]
Since EL7 version systemd has been adopted.

So when trying it on Centos 7 I have the following error:

```
TASK: [groover.tomcat | Install sysvinit Tomcat Service] ********************** 
fatal: [localhost] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'ansible_local' is undefined", 'failed': True}
fatal: [localhost] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'ansible_local' is undefined", 'failed': True}
```

Do you think is possible to enhance the role to support EL7 platform?

**Comment by spul** [comment]
Hi,

systemd support right now is bad. This one tries to install a SysV script which is bad on EL7. Running tomcat with systemd requires jsvc, ... A lot of stuff which is currently not implemented, but we are working on it. Stay tuned.

**Comment by kakawait** [comment]
I have started EL7 support on my side. But first time playing with Ansible, if you have time to check modification I have committed on https://github.com/kakawait/ansible-tomcat/tree/el7-support.

If it is not so bad I can create a PR.

**Comment by spul** [comment]
I'd greatly appreciate PR on systemd support, especially for jsvc with ansible_os_family == RedHat.

**Comment by kakawait** [comment]
Ok I will run integration tests before PR (just tested manually atm)... Coming soon :)

**Comment by kakawait** [comment]
And any reason to choose jsvc over possible java wrapper? Jsvc forces output and error file to be root owner and you can't easily rotate logs...

**Comment by kakawait** [comment]
Any reason to use JSVC over systemd directly to manage tomcat lifecycle?

**Comment by spul** [comment]
Not an expert on that matter. From my understanding it's best to hand control over the processes to systemd completely, which is fine with jsvc. Wrapper like tanuki which in turn is managed with a shell script is not an option for systemd as systemd does not support running services without binaries. So either way it would be required to "wrap" tanuki binary or use jsvc. 
Archlinux community suggests jsvc for java applications with systemd. Mostly these guys know what they are talking about. Long story short: I need to dive deeper into this.
Priority for now is 

* several fixes with local download and upload of redistributables
* support for tomcat 8
* fix systemd support.

**Comment by kakawait** [comment]
Ok no probs. I'm neither ops or devops, I'm just a developer so I used to take the shortest way (avoiding security or other aspect hihi).

Actually my fork works goods on jsvc on Centos7 but I will take much time to improve logging:

- Jsvc is dumping tomcat log in `-errfile` instead of `-outfile` even there is no error (o.O).
- I didn't find a way to create a `catalina.out` per `CATALINA_BASE` with correct owner (`tomcat` user)

**Comment by spul** [comment]
Thanks for all the hints. I'll take all of them into account when I start on systemd/jsvc/wrapper stuff. I'll keep you updated.

**Comment by kakawait** [comment]
Some information about systemd vs jsvc (in case): http://stackoverflow.com/questions/28894008/what-benefit-do-i-get-from-jsvc-over-just-using-systemd

Otherwise thanks for quick support (and your ansible playbooks are really great, I have to change my old java playbook to yours ^^)

**Comment by spul** [comment]
Todos marked earlier are all implemented now. I'll have to wait for internal PR before releasing to general public. Stay tuned.

**Comment by spul** [comment]
Hi, have a look at [feature/fix-systemd-instance-management](https://github.com/silpion/ansible-tomcat/tree/feature/fix-systemd-instance-management) branch. This will be the next release with fixes for all issues 

* [#6]
* [#7]
* [#8]

**Comment by kakawait** [comment]
Nice I will check that at the end of week.

**Comment by spul** [comment]
Implemented/fixed with current release.
