### ISSUE TITLE
Support tomcat 8 natively

### ISSUE THREAD

**Issue by kakawait** [silpion/ansible-tomcat#8]
Tomcat 8 removed `JasperListener`.

Using the following template https://github.com/silpion/ansible-tomcat/blob/master/templates/server.xml.j2#L21 Tomcat 8 boot failed.

I know we can add our custom template by using `tomcat_server_xml_template` but it can be great to support Tomcat 8 natively because Tomcat 7 becomes an old man :)

**Comment by spul** [comment]
Hi, I've a local feature branch for tomcat8 already which has JasperListener removed for tomcat 8.

**Comment by spul** [comment]
Implemented with current release. Sorry for the long time to wait. If in doubt have a look at [my post](https://groups.google.com/forum/#!topic/ansible-project/kgf92KMDinE) to ansible-project mailing list.
